name = "tana-worker"
main = "src/worker.ts"
compatibility_date = "2024-01-29"

r2_buckets = [{ binding = "MY_BUCKET", bucket_name = "worker-r2-demo" }]
kv_namespaces = [
    { binding = "tana_storage", id = "b8b4b159fc674a5db963e37cf5dbecb3" },
]
